### ISSUE TITLE
usage in travis-ci

### ISSUE THREAD

**Issue by typekpb** [mattbrictson/chandler#14]
I'd love to automate this process for my project.
Would you mind documenting a way to sync changelog in travis-ci build? I'd love to do this once I tag my project. Any chance for that?

**Comment by mattbrictson** [comment]
Hi, thanks for the suggestion!

As currently designed, chandler relies on a `~/.netrc` file to authenticate to GitHub. For a Travis CI build, I'm not sure if this is possible. I don't know enough about Travis to say whether you can do this in a way that does not expose the password or OAuth token.

However, assuming the netrc thing can be solved, then it should just be a matter of adding these commands to the build steps:

```
gem install chandler
chandler push
```

That will sync the release notes for all tags to GitHub.

If anyone wants to suggest a solution, feel free to open a PR for the README or add your comments here.

**Comment by typekpb** [comment]
Thanks for response. Will give it a try and let you know.

**Comment by orta** [comment]
In theory, this could use the [deploy](https://github.com/artsy/emission/pull/263/files#diff-354f30a63fb0907d4ad57269548329e3R17) section on the travis.yml - which [sets up](https://github.com/artsy/emission/pull/263/files#diff-351ad86330040c359accbf3fce73d9d7R4) the `.netrc`

Note that travis' deploy script is run on [ruby 1.9.3](https://docs.travis-ci.com/user/deployment/script/) - so you may have to update, then `gem install`

**Comment by orta** [comment]
Another option is to run it as a part of a [GitHub Releases](https://docs.travis-ci.com/user/deployment/releases/) script, which I don't know enough about to give useful advice on, however you can run pre-release scripts ( and maybe the setup github token is accessible in the ENV during that stage? )

**Comment by mattbrictson** [comment]
@orta Thanks for the tips and ideas!

@typekpb If you'd like to try this out, you could create a simple script and reference it in the `deploy` section of your `travis.yml`. The script would need to do this:

* `gem install chandler`
* Create a `.netrc` file so that it contains the desired GitHub username and OAuth token
* `chandler push $TRAVIS_TAG`

Also, I'm guessing you'd probably only want the script to run when `$TRAVIS_TAG` is present.

> TRAVIS_TAG: If the current build is for a git tag, this variable is set to the tag’s name.

You could store the OAuth token as an [encrypted environment variable](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml).

And, as @orta mentioned, you'll need to run the deploy script in a newer version of Ruby, since chandler requires Ruby 2.1+ and the default Ruby used by Travis is 1.9.3.

One way we could make this slightly simpler is if chandler could use environment variables for the GitHub credentials, and bypass the need to set up a `.netrc` file. Perhaps it could check for the presence of `$GITHUB_USERNAME` and `$GITHUB_TOKEN` or something like that.

Anyway, let me know if you get this working, and if you need my help to make any modifications to chandler itself. Thanks!

**Comment by typekpb** [comment]
@mattbrictson  @orta thanks a lot guys for your help!

I finally managed it. However it's been rather a painful process, let me document the steps required:

1. relevant `.travis.yml` chunks (please note I'm using go with sudo: false, not sure about other setups):
	
		language: go
		sudo: false 
		...
		before_deploy:
		  # chandler needs ruby version >= 2.2 => install it via rvm (reuse travis installed one)
		  - ruby -v && rvm install 2.3.1 && rvm use --default 2.3.1 && ruby -v
		  - ./travis/before_deploy.sh

1. `./travis/before_deploy.sh` chunk:

		#!/bin/bash
		...
		gem install --no-ri --no-rdoc chandler

		# setup credentials
		cp -f travis/.netrc ~/.netrc
		chmod 600 ~/.netrc
		sed -i.bak "s/###OAUTH_LOGIN###/${OAUTH_LOGIN}/" ~/.netrc
		sed -i.bak "s/###OAUTH_TOKEN###/${OAUTH_TOKEN}/" ~/.netrc
		 
		chandler --changelog=$(pwd)/docs/CHANGELOG.md --github=foo/foo push

1. `./travis/.netrc` contents:

		machine api.github.com
		  login ###OAUTH_LOGIN###
		  password ###OAUTH_TOKEN###

1. moreover I had to setup environment variables in the travis-ci, namely: `OAUTH_LOGIN` and `OAUTH_TOKEN`

Well, as you mentioned, it would be really nice, if we could skip `~/.netrc` part and use env vars only. Any chance to use the secured ones directly in the .travis.yml (via: `secure: ...`) ? As I'm worried about getting them exposed somehow anyway in a way I use those.

**Comment by orta** [comment]
Secured tokens would work - I have a branch that [would work](https://github.com/mattbrictson/chandler/compare/master...orta:token?expand=1) with it, but I'm finding it really hard to test my changes.

**Comment by typekpb** [comment]
if you need a test volunteer, I'd be happy give it a try on my project, the only issue would be: how to install the version you're referring to on travis?

**Comment by orta** [comment]
You'd have to use a Gemfile:

```
gem 'chandler', :git => "https://github.com/orta/chandler.git", :branch => "token"
```

pretty arduous

**Comment by typekpb** [comment]
well, it's a golang project, but if you provide me with a steps, I'd be happy to (as I hope this could find it's way to official release)

**Comment by orta** [comment]
Until it's shipped as a part of chandler, it's arguably more effort to do than what you have right now ( suddenly you have ruby dependency management to handle on-top of your usual bits ) - I'd recommend against it for this second

**Comment by mattbrictson** [comment]
@orta Your branch is looking great so far! Is there any way I can help you get it ready to merge?

Perhaps to make testing easier, you could put the Octokit logic in `Chandler::Configuration`, like this:

```ruby
module Chandler
  class Configuration
    # ...

    def octokit
      @octokit ||= begin
        # construct with :access_token or :netrc, based on ENV
      end
    end
  end
end
```

And then change `Chandler::GitHub` to use `config.octokit` instead of calling `Octokit::Client.new`.

That way you can unit test the ENV-based logic independently in `configuration_test.rb`; that should be sufficient without needing to do an integration test, IMO.

**Comment by mattbrictson** [comment]
@typekpb I merged #16 and released chandler 0.5.0 with GitHub auth token environment variable support, thanks to @orta's contribution. Give it a shot!

**Comment by orta** [comment]
And this is how we do it on Danger in Travis too: https://github.com/danger/danger/pull/620

Thanks @mattbrictson

**Comment by mattbrictson** [comment]
@typekpb Did you get this working? I'd like to close this issue, unless there is more that Chandler needs to do to support Travis.

**Comment by mattbrictson** [comment]
I'm considering this solved. Closing.
