### ISSUE TITLE
Allow other formats

### ISSUE THREAD

**Issue by bogren** [mattbrictson/chandler#20]
Is it be out of scope for this project to allow other formats of the CHANGELOG file e.g yaml?  

Edit: if not, I'd love to contribute.

**Comment by mattbrictson** [comment]
Right now I think that would be out of scope. Chandler was heavily inspired by <http://keepachangelog.com/>, and a YAML format seems to run counter to the spirit of those recommendations. I'm curious, though: is there a particular project you know of that uses a YAML CHANGELOG?

**Comment by bogren** [comment]
Yes, I can think of two, [eigen](https://github.com/artsy/eigen/blob/master/CHANGELOG.yml) by Artsy, our project (private repo). 

Another solution I can think of is to run a script to create a temp changelog in markdown and use that with chandler to update the release notes :) (There are several parses for yaml 👉  markdown)

**Comment by mattbrictson** [comment]
Interesting! In this case, since your CHANGELOG is already machine-readable, I don't think Chandler adds much value. If you want, you could write a Ruby script that uses the `Chandler::GitHub` class, or you could use [Octokit](https://github.com/octokit) directly, once you pull the appropriate description out the YAML. Or, like you said, you could generate Markdown from the YAML first, but that seems like overkill.

I'll close this issue because I still think this is out of scope for now.
